// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: api/proto/aegis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AegisSentinel_Connect_FullMethodName       = "/proto.AegisSentinel/Connect"
	AegisSentinel_SendHeartbeat_FullMethodName = "/proto.AegisSentinel/SendHeartbeat"
	AegisSentinel_SendAlert_FullMethodName     = "/proto.AegisSentinel/SendAlert"
	AegisSentinel_CommandStream_FullMethodName = "/proto.AegisSentinel/CommandStream"
)

// AegisSentinelClient is the client API for AegisSentinel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AegisSentinelClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	SendAlert(ctx context.Context, in *AlertRequest, opts ...grpc.CallOption) (*AlertResponse, error)
	CommandStream(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandMessage], error)
}

type aegisSentinelClient struct {
	cc grpc.ClientConnInterface
}

func NewAegisSentinelClient(cc grpc.ClientConnInterface) AegisSentinelClient {
	return &aegisSentinelClient{cc}
}

func (c *aegisSentinelClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, AegisSentinel_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisSentinelClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AegisSentinel_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisSentinelClient) SendAlert(ctx context.Context, in *AlertRequest, opts ...grpc.CallOption) (*AlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertResponse)
	err := c.cc.Invoke(ctx, AegisSentinel_SendAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisSentinelClient) CommandStream(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AegisSentinel_ServiceDesc.Streams[0], AegisSentinel_CommandStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandRequest, CommandMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AegisSentinel_CommandStreamClient = grpc.ServerStreamingClient[CommandMessage]

// AegisSentinelServer is the server API for AegisSentinel service.
// All implementations must embed UnimplementedAegisSentinelServer
// for forward compatibility.
type AegisSentinelServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	SendAlert(context.Context, *AlertRequest) (*AlertResponse, error)
	CommandStream(*CommandRequest, grpc.ServerStreamingServer[CommandMessage]) error
	mustEmbedUnimplementedAegisSentinelServer()
}

// UnimplementedAegisSentinelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAegisSentinelServer struct{}

func (UnimplementedAegisSentinelServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAegisSentinelServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedAegisSentinelServer) SendAlert(context.Context, *AlertRequest) (*AlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAlert not implemented")
}
func (UnimplementedAegisSentinelServer) CommandStream(*CommandRequest, grpc.ServerStreamingServer[CommandMessage]) error {
	return status.Error(codes.Unimplemented, "method CommandStream not implemented")
}
func (UnimplementedAegisSentinelServer) mustEmbedUnimplementedAegisSentinelServer() {}
func (UnimplementedAegisSentinelServer) testEmbeddedByValue()                       {}

// UnsafeAegisSentinelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AegisSentinelServer will
// result in compilation errors.
type UnsafeAegisSentinelServer interface {
	mustEmbedUnimplementedAegisSentinelServer()
}

func RegisterAegisSentinelServer(s grpc.ServiceRegistrar, srv AegisSentinelServer) {
	// If the following call panics, it indicates UnimplementedAegisSentinelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AegisSentinel_ServiceDesc, srv)
}

func _AegisSentinel_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisSentinelServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisSentinel_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisSentinelServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisSentinel_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisSentinelServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisSentinel_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisSentinelServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisSentinel_SendAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisSentinelServer).SendAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisSentinel_SendAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisSentinelServer).SendAlert(ctx, req.(*AlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisSentinel_CommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AegisSentinelServer).CommandStream(m, &grpc.GenericServerStream[CommandRequest, CommandMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AegisSentinel_CommandStreamServer = grpc.ServerStreamingServer[CommandMessage]

// AegisSentinel_ServiceDesc is the grpc.ServiceDesc for AegisSentinel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AegisSentinel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AegisSentinel",
	HandlerType: (*AegisSentinelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _AegisSentinel_Connect_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _AegisSentinel_SendHeartbeat_Handler,
		},
		{
			MethodName: "SendAlert",
			Handler:    _AegisSentinel_SendAlert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CommandStream",
			Handler:       _AegisSentinel_CommandStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/aegis.proto",
}
